### PR TITLE
feat(query): support collectionGroup for listeners - @rscotten

### PR DESCRIPTION
**Pull request by rscotten**
### Description

This adds listener support for Firestore collection groups.  So you can now do this:

```typescript
  firestoreConnect(() => [
    {
      collectionGroup: 'todos'
    }
  ]),
```

and this

```typescript
  this.props.firestore.setListener({
    collectionGroup: 'todos',
  });
```

### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [x] Docs updated with any changes or examples if applicable
- [x] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by rscotten** [comment]
@prescottprue If and after this gets merged, I'll submit another PR for `react-redux-firebase` with updated Typescript typings.

**Comment by prescottprue** [comment]
Thanks for catching this. Whats weird is that [there is some logic already in place for `collectionGroup`](https://github.com/prescottprue/redux-firestore/blob/b5d5f312a078cb41f3d297863bd67df332a5e265/src/utils/query.js#L135) - I'll have to go back through the history to find why it was missed, but glad we got it now!

**Comment by prescottprue** [comment]
It appears it was [this PR](https://github.com/prescottprue/redux-firestore/pull/233) - looks like it was only added to a few of the query utils. Again, thanks for finding this

**Comment by prescottprue** [comment]
Thanks for the PR - released in [v0.12.0](https://github.com/prescottprue/redux-firestore/releases/tag/v0.12.0)

**Pull request merged**
