### PR TITLE
Add firestore reducer for typescript

### PR DESCRIPTION
**Pull request by bawahakim**
### Description

I couldn't properly get firestore to work with Typescript, so I went ahead and tried implementing it. 

### Check List
If not relevant to pull request, check off as complete

- [x] All tests passing
- [ ] Docs updated with any changes or examples if applicable
- [ ] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by msutkowski** [comment]
@feelthepain444 You might want to check this out this PR I closed: https://github.com/prescottprue/react-redux-firebase/pull/964. I'd be happy to collaborate with you on this - I meant to open this against the `typescript` branch here, but I have no clue as to what's going on with this repo so I've just been keeping my types locally.

Regardless, you'd want to return a `Reducer` type from `redux` on `firestoreReducer`, otherwise you'd still have to cast in `combineReducers`. And `FirestoreReducer.Reducer` should probably be more like `FirestoreReducer.State`.

**Comment by alexandermckay** [comment]
@msutkowski 

@bawahakim is no longer using `redux-firestore` or `react-redux-firestore` [link](https://github.com/prescottprue/redux-firestore/issues/295#issuecomment-673544662).

I am guessing here but I assume he understandably won't want to spend anymore time on this. I will fork his repo over the weekend and add the changes you've suggested.

**Comment by devth** [comment]
Did anything ever progress with this?

**Comment by prescottprue** [comment]
[v0.15.0 release](https://github.com/prescottprue/redux-firestore/releases/tag/v0.15.0) has the functionality based on code here and @msutkowski mentioned PR - because of that both of you were listed as co-authors of the commit while I was manually combining it

This is a first swing at the types, but it seemed to be working in a simple example. Please reach out if things aren't working as expected!

**Pull request closed without merging**
