### PR TITLE
fix(query): fix document updates by using deep clone on doc change event

### PR DESCRIPTION
**Pull request by compojoom**
### Description
Our team ran into an issue. We were listening to a collection with 3 documents, then we remove the 3 documents in a batch, but redux-firestore only removes one. 

It turned out that it is because redux-firestore adds a doc property to the meta object. The meta object should actually be a copy of the original meta, but since we don't do a deep clone there we end up modifying the original object.

### Check List
If not relevant to pull request, check off as complete

- [ ] All tests passing
- [ ] Docs updated with any changes or examples if applicable
- [ ] Added tests to ensure new feature(s) work properly

### CODE REVIEW

**Comment by prescottprue** [comment]
Nice work finding this and making the PR! I'm going to look into why the test is failing before merging, but definitely going to try to get it in soon.

**Comment by compojoom** [comment]
I'm looking at the failing test. 

It fails at the last line `expect(dispatchSpy).to.be.calledWith(expectedAction);`

```
AssertionError: expected spy to have been called with arguments {
  meta: { collection: "test", doc: "1", subcollections: [{ collection: "test2" }] },
  payload: { name: "test/1/test2/123ABC" },
  type: "@@reduxFirestore/SET_LISTENER"
}
````

what is this payload.name? Why do we expect to have this? here is the reset of the output
image

So the green is - the expected output, the red is the actual output? The actual output looks correct to me.

If we have a document modified -> the nwe have the doc property on the subcollection and the path seems correct. 

If we have a set_listener -> then the payload.name doesn't need to have the doc id from the previous response.

**Comment by compojoom** [comment]
I fixed the test by removing. the ${docChanges[0].doc.id} from the payload.name

We expect to have a SET_LISTENER on the subcollection test2, not a set_listener on the subcollection test2 and doc ABC.

@prescottprue - what do you think? Is my change correct, or am I missing something here?

**Comment by compojoom** [comment]
what is with the lint rule fail? How do you want to fix it with - eslint-disable-next-line?
the consistent return expect us to always have a value
https://eslint.org/docs/2.0.0/rules/consistent-return

but fiew lines before the returns it complains about we do:
```
        // Parameter/child of list item does not exist
        if (!idOrList) {
          return;
        }
```

problem is, so far I understand it:
https://stackoverflow.com/questions/33266946/how-to-stop-lodash-js-each-loop

that if we do return false -> we'll break the loop. and we need to return nothing in order to do continue...

**Comment by prescottprue** [comment]
@compojoom Yeah, you can just do:

```js
// Parameter/child of list item does not exist
if (!idOrList) {
  return; // eslint-disable-line consistent-return
}
```

If it wraps onto the next line then you can do:

```
/* eslint-disable consistent-return */
// Parameter/child of list item does not exist
if (!idOrList) {
  return;
}
/* eslint-enable consistent-return */
```

**Comment by compojoom** [comment]
wow, I think I made travis happy. Can we merge this in 0.7.3?

**Comment by prescottprue** [comment]
@compojoom Yup, thats what I was waiting to release it for! Thanks

**Comment by compojoom** [comment]
wohooo!

**Pull request merged**
